USE GAGARAGE;

CREATE LOGIN Secretaire WITH PASSWORD = 'Tigrou007', CHECK_POLICY = OFF;
CREATE LOGIN Directeur WITH PASSWORD = 'Tigrou007', CHECK_POLICY = OFF;
CREATE LOGIN Administrateur WITH PASSWORD = 'Tigrou007', CHECK_POLICY = OFF;
CREATE LOGIN Livreur WITH PASSWORD = 'Tigrou007', CHECK_POLICY = OFF;
CREATE LOGIN Garagiste WITH PASSWORD = 'Tigrou007', CHECK_POLICY = OFF;

CREATE USER Garagiste FOR LOGIN Garagiste;

CREATE USER Secretaire FOR LOGIN Secretaire;
CREATE USER Directeur FOR LOGIN Directeur;
CREATE USER Administrateur FOR LOGIN Administrateur;
CREATE USER Livreur FOR LOGIN Livreur;

CREATE ROLE Admi;
CREATE ROLE Dir;
CREATE ROLE Liv;
CREATE ROLE Gar;
CREATE ROLE Sec;

ALTER ROLE Admi ADD MEMBER Administrateur;
ALTER ROLE Dir ADD MEMBER Directeur;
ALTER ROLE Liv ADD MEMBER Livreur;
ALTER ROLE Sec ADD MEMBER Secretaire;
ALTER ROLE Gar ADD MEMBER Garagiste;



GRANT SELECT, INSERT, UPDATE, DELETE ON PAYS TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON VILLE TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADRESSE TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON PERSONNE TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACCES TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON GARAGE TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON EMPLOYE TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON VEHICULE TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON FOURNISSEUR TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON PIECE TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTERVENTION TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON FACTURE TO Admi;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIVRAISON TO Admi;

GRANT SELECT, INSERT, UPDATE ON PAYS TO Dir;
GRANT SELECT, INSERT, UPDATE ON VILLE TO Dir;
GRANT SELECT, INSERT, UPDATE ON ADRESSE TO Dir;
GRANT SELECT, INSERT, UPDATE ON PERSONNE TO Dir;
GRANT SELECT, INSERT, UPDATE ON ACCES TO Dir;
GRANT SELECT, INSERT, UPDATE ON GARAGE TO Dir;
GRANT SELECT, INSERT, UPDATE ON EMPLOYE TO Dir;
GRANT SELECT, INSERT, UPDATE ON VEHICULE TO Dir;
GRANT SELECT, INSERT, UPDATE ON FOURNISSEUR TO Dir;
GRANT SELECT, INSERT, UPDATE ON PIECE TO Dir;
GRANT SELECT, INSERT, UPDATE ON INTERVENTION TO Dir;
GRANT SELECT, INSERT, UPDATE ON FACTURE TO Dir;
GRANT SELECT, INSERT, UPDATE ON LIVRAISON TO Dir;

GRANT SELECT ON ADRESSE TO Liv;
GRANT SELECT ON ACCES TO Liv;
GRANT SELECT ON GARAGE TO Liv;
GRANT SELECT ON VEHICULE TO Liv;
GRANT SELECT, UPDATE ON PIECE TO Liv;
GRANT SELECT, INSERT, UPDATE ON FACTURE TO Liv;
GRANT SELECT, INSERT, UPDATE ON LIVRAISON TO Liv;

GRANT SELECT ON ACCES TO Gar;
GRANT SELECT ON VEHICULE TO Gar;
GRANT SELECT ON PIECE TO Gar;
GRANT SELECT, UPDATE ON INTERVENTION TO Gar;
GRANT SELECT, UPDATE ON FACTURE TO Gar;
GRANT SELECT, UPDATE ON LIVRAISON TO Gar;

GRANT SELECT, INSERT, UPDATE ON PAYS TO Sec;
GRANT SELECT, INSERT, UPDATE ON VILLE TO Sec;
GRANT SELECT, INSERT, UPDATE ON ADRESSE TO Sec;
GRANT SELECT, INSERT, UPDATE ON PERSONNE TO Sec;
GRANT SELECT, INSERT ON ACCES TO Sec;
GRANT SELECT, INSERT, UPDATE ON EMPLOYE TO Sec;
GRANT SELECT, INSERT, UPDATE ON VEHICULE TO Sec;
GRANT SELECT, INSERT, UPDATE ON FOURNISSEUR TO Sec;
GRANT SELECT, INSERT, UPDATE ON PIECE TO Sec;
GRANT SELECT, INSERT, UPDATE ON INTERVENTION TO Sec;
GRANT SELECT, INSERT, UPDATE ON FACTURE TO Sec;
GRANT SELECT, INSERT, UPDATE ON LIVRAISON TO Sec;